# Week 3: Linear Systems

In [1]:
import numpy as np
import scipy.linalg

### Problem 1:

In [2]:
A = np.array([
    [0.5, 0.2, 0.1],
    [0.3, 0.5, 0.2],
    [0.2, 0.3, 0.7]
])

b = np.array([0.3e2, 0.4e2, 0.3e2])

print("A = ", A, " ","b = ", b)

x = np.linalg.solve(A, b)
print(f'x = {x}')
sum = np.sum(x)
print(f'verified sum ({sum})')

A =  [[0.5 0.2 0.1]
 [0.3 0.5 0.2]
 [0.2 0.3 0.7]]   b =  [30. 40. 30.]
x = [36.36363636 54.54545455  9.09090909]
verified sum (100.0)


### Problem 2:

In [3]:
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
])
b = np.array([8, -11, -3])
print(np.linalg.solve(A, b))

[ 2.  3. -1.]


### Problem 3:

In [4]:
# C3H8 + bO2 -> cCO2 + dH2O
# carbon balance: 3 = c [c-3=0]
# oxygen balance: 2b = 2c + d  [2c-2b+d=0]
# hydrogen balance: 8 = 2d  [2d-8=0]

# i.e. A = [[0, 1, 0], [2, -2, 1], [0, 0, 2]]
#      b = [3, 0, 8]

A = np.array([[0, 1, 0], [2, -2, 1], [0, 0, 2]])
b = np.array([3, 0, 8])
x = np.linalg.solve(A, b)
print(x)

[1. 3. 4.]


### Problem 4:

In [5]:
# P = Q1R1 = Q2R2 = Q3R3, q1+q2+q3=12, (r1, r2, r3) = (2, 3, 4)
# 2Q1-P=0
# 3Q2-P=0
# 4Q3-P=0
A = np.array([
    [2, 0, 0, -1],
    [0, 3, 0, -1],
    [0, 0, 4, -1],
    [1, 1, 1, 0]
])
b = np.array([0, 0, 0, 12])

x = np.linalg.solve(A, b)
print(x)

# both checks are verified (lowest resistance branch carries most flow, and also all the pressures are same)

[ 5.53846154  3.69230769  2.76923077 11.07692308]


### Problem 5:

In [6]:
A = np.array([
    [1, 2, -1],
    [2, 4, -2],
    [3, 1, 0]
])
det = np.linalg.det(A)
print(det)

b = np.zeros(3)

try:
    x = np.linalg.solve(A, b)
    print(x)
except Exception as e:
    print(e, "-> cant solve")

0.0
Singular matrix -> cant solve


### Problem 6: